### ISSUE TITLE
Getting Errors when Create Actor | Monster

### ISSUE THREAD

**Issue by sirkerry** [Forelius/fantastic-depths#1]
When creating a Monster actor type FVTT is throwing the following errors:

**Error: Failed data preparation for Actor.. Cannot read properties of undefined (reading 'hd')** - does this twice, then
**Error: Failed data preparation for Actor.iGQ3cEoYThAt5fwf. Cannot read properties of undefined (reading 'hd')**

Then is creates the Actor, but when you click on it, it doesn't open, FVTT throws the following error:

Error: An error occured while rendering fadeActorSheet 74. Cannot read properties of undefined (reading 'replace')

The errors all appear to be coming from foundry.js:655.

Running FVTT 12.331, FD 0.3.6, no modules, using Electron on Win11

**Comment by Forelius** [comment]
I can reproduce that and will fix.

**Comment by Forelius** [comment]
Fixed in release v0.3.8
