### ISSUE TITLE
Skills/Abilities Automation

### ISSUE THREAD

**Issue by sarfayff** [Forelius/fantastic-depths#14]
General skills that affect Stats (such as Attack Rolls, Damage Rolls, Opening Doors) 
e.g. blind shooting affects Attack Rolls
e.g. rapid fire affects Attack Rolls
e.g. muscle affects Opening Doors/Lifting Bars or encumbrances

Abilities that affects Stats

They will affect attack rolls.

So helpful if these are automatically factored in. 

Suggest Solution
Successful use of a skill will grant a condition.
Automation will check whether there is such condition. If so, apply the benefits.
Once the benefit is used, remove the condition.

**Comment by Forelius** [comment]
Some of these features already exist and others are beyond scope that I have planned for the system.
