### ISSUE TITLE
The NPC Actor Type has Skills menu showing up twice

### ISSUE THREAD

**Issue by sirkerry** [Forelius/fantastic-depths#2]
![image](https://github.com/user-attachments/assets/5809464d-115e-466e-8ec9-75c7f2d06ada)

**Comment by Forelius** [comment]
That doesn't surprise, me as I've sort of ignored the NPC sheet and might remove it, allowing the character sheet to be configurable as an NPC.

**Comment by Forelius** [comment]
In release v0.3.8
