### ISSUE TITLE
Feature Request: Add Tags to Spells

### ISSUE THREAD

**Issue by sirkerry** [Forelius/fantastic-depths#22]
I would like to see the Tags feature (like Items, Weapons and Monsters have) added to Spells.

Use case: it would make it easy to create effect that act upon groups of spells defined by common tags.

The real reason I would like this: so I can have MU spell schools and Cleric spheres/domains easily if I want to for some reason (i.e. say I wanted to run something set in GAZ3's Glantri).

**Comment by Forelius** [comment]
Implemented in v0.4.7
