### ISSUE TITLE
Customization Feature Request: Exploration

### ISSUE THREAD

**Issue by sirkerry** [Forelius/fantastic-depths#24]
The ability to change via game settings the text being displayed for the 4 Exploration rolls on the character sheets and chat cards for the rolls.

Also, would be really cool to have the ability to toggle if the roll is greater than, less than, greater than or equal to, or less than or equal to.

**Comment by Forelius** [comment]
Regarding the text, I'd recommend the same thing that I did for the saving throws. Create a module or make change locally to the localization text.
Regarding configurable exploration rolls, it seems doable, but not a high priority right now.

**Comment by Forelius** [comment]
I think the way this will be implemented is with a redesign of the UI. The exploration section of the character sheet will be removed and exploration skills will be available in the skills tab.

**Comment by Forelius** [comment]
This will be in the upcoming release and the way I've implemented it is to use the special abilities item. I've added additional properties to the special ability item in order to facilitate these exploration checks.

**Comment by Forelius** [comment]
I'm going to close this for now. In a later task, I will redesign the character sheet to hide the 4 exploration checks based on a config setting.
