### ISSUE TITLE
NPC Actor Type Description Feature Request

### ISSUE THREAD

**Issue by sirkerry** [Forelius/fantastic-depths#3]
Can the NPC Actor Type also have the fields of Sex, Age, Height, Weight, and Languages like the Character Actor Type does as part of Description?

**Comment by Forelius** [comment]
I'm not sure, because the character sheet might end up being the NPC sheet. I've already added a checkbox on the character sheet to signify the character is a retainer, but haven't done anything with it yet. So maybe the NPC sheet is going away, because it seems redundant.

**Comment by Forelius** [comment]
In release v0.3.8
