### ISSUE TITLE
Breath Weapon damage not applied

### ISSUE THREAD

**Issue by fougerec** [Forelius/fantastic-depths#34]
It seems like Breath Weapon attacks don't allow the damage to be applied
![image](https://github.com/user-attachments/assets/6cade2c8-5185-4c77-8bfd-356bcfd3b05b)

**Comment by Forelius** [comment]
It looks like breath damage mitigation is blocking all of the breath damage. I'll look into it and fix it. Thanks for reporting the issue.

**Comment by Forelius** [comment]
Tested in v0.6.1 and it is working for me.
