### ISSUE TITLE
Not Possible To Roll Weapons and Skills From Actor Without a Token

### ISSUE THREAD

**Issue by JordanRR** [Forelius/fantastic-depths#36]
I'm not sure if it's a bug or a feature, but I think an actor should be able to use an ability (and a weapon; basically everything on an actor's sheet) without a token on a scene. There are many times where that could be useful (on an overland map, while doing theater of the mind simple combat, etc.)

Thanks!

**Comment by Forelius** [comment]
Agreed. I will add it to the backlog.

**Comment by Forelius** [comment]
This one is sort of tricky due to the fact that Fantastic Depths combat code works with tokens as opposed to actors. I'll have to fallback to the source actor if no token for the actor exists on the canvas/map.

**Comment by Forelius** [comment]
After digging deeper, it looks like monster attack rolls  work, but character attacks, all damage rolls and saving throw rolls are not working. I think damage rolls could be fixed, but not sure how saving throw would work if no token is selected. Maybe I could default to the player's main character for saving throws that don't have a token selected.

**Comment by Forelius** [comment]
Even after this is implemented, there will be limits to what can be done. For instance, with tokens a single orc actor can be duplicated five times on the map and a unique actor is created for each token, assuming actor link is disabled, which it is by default for monsters. Without tokens you'd have to create five duplicate actors and all apply damage and saving throws would have to be done manually with the character sheet.

**Comment by JordanRR** [comment]
Yes, allowing to roll from the actor without a token is not a great idea if you want to track HP and stuff like that for unlinked actor/token. This is going to be most useful for linked actor/token, but could still see some use for unlinked ones (especially for testing purposes, but sometimes even during play). The simple fact that it won't make people submit bug report when they fail to roll an ability might be worth it ;) I was toying around your system and could not understand what I was doing wrong when testing stuff, until I thought of putting a token on a scene.

**Comment by Forelius** [comment]
Implemented in v0.6.1
