### ISSUE TITLE
Items and Active Effects?

### ISSUE THREAD

**Issue by sirkerry** [Forelius/fantastic-depths#4]
Any chance of adding Active Effects to the 4 item types (General Skill, Special Ability, Spell, and Weapon Mastery) that don't currently have them or at least to Spells and Special Abilities?

**Comment by Forelius** [comment]
Maybe. Can you give me an example of how it would work for a spell or special ability, just abstract, not technical. Or if there is another system that has that functionality I can look at that.

**Comment by sirkerry** [comment]
ARS and DND5e have this, but you know thinking about this, what might work is basically a Spell 'Item' kind of like a condition that could be added to an actor but not show up as part of the regular item inventory. Use cases would be to handle things like curses, blessings and temporary items like 'mage armor' although something like mage armor most likely should show up in the regular inventory?

**Comment by Forelius** [comment]
Oh I see what you mean now. I like it, but will have to let that one marinate for awhile, because I'm not sure exactly how I'd want to implement that.

**Comment by Forelius** [comment]
Moved this to issue #30
