### ISSUE TITLE
Bug? Uncaught ReferenceError 

### ISSUE THREAD

**Issue by JordanRR** [Forelius/fantastic-depths#44]
I was trying to get the data paths for items using the code provided by Foundry, and this pops up in the console (pc client, using v12.331, FADE 0.6.11) : 
![image](https://github.com/user-attachments/assets/36079809-792f-49b5-9bd0-d54a5bb55953)

I have no idea if I did something wrong or if there is something of interest for you here, unfortunately.

**Comment by Forelius** [comment]
I don't think it's a defect in the fantastic-depths system. That script would need to be modified to point to the correct system id. Wherever you see SYSTEM_ID in the script, replace that with "fantastic-depths". "fantastic-depths" needs to be in quotes.
