### ISSUE TITLE
Suggestion for active effects : add dice notation for duration

### ISSUE THREAD

**Issue by JordanRR** [Forelius/fantastic-depths#46]
Suggestion: the duration field in the active effect would accept dice notration. Useful for potions, for example, that last 1d6+6 turns.

**Comment by Forelius** [comment]
The effects are built-in functionality that come with foundry. FADE just taps into whatever Foundry already has for effects. I'd have to re-implement effects to do something like that and I don't plan on doing that. Cool idea though.
