### ISSUE TITLE
Issue : classic encumbrance considers 2400 instead of 1600.

### ISSUE THREAD

**Issue by JordanRR** [Forelius/fantastic-depths#47]
On a PC and monster sheet, encumbrance is 2400 ionstead of 1600 when classic is enabled.

Cannot confirm for NPC sheet because I can't open it right now. (Another issue.)

**Comment by Forelius** [comment]
The GM Only tab contains the Max Encumbrance and that will default to 2400 for characters. I thought about making the setting change that, but people might use custom values and so I decided to leave that as a manual change.
