### ISSUE TITLE
Tags on Monster Actor Types

### ISSUE THREAD

**Issue by sirkerry** [Forelius/fantastic-depths#5]
I really like the idea of Tags on Items (reminds me of a bit of the Types implementation in the ARS game system), any chance of expanding the tags in include Monster actor types?

Use case would be to tag the appropriate monsters say dragon or goblinoid and have characters or items with active effects that apply if certain tags are detected on targeted token's actor when attacked.

**Comment by Forelius** [comment]
Good idea, I will add it to the backlog.

**Comment by Forelius** [comment]
In release v0.3.8
