### ISSUE TITLE
Minor UI/UX suggestion: level on the saving throws class sheet should be *first* level, not last level

### ISSUE THREAD

**Issue by JordanRR** [Forelius/fantastic-depths#59]
Right now, if I write new saves at say level 1 and level 3, the PC sheet update the saves on level 2, because the system understands the level as the last one (so last one for the firsat line is level 1, so change at level 2 up to level 3, etc.) It works fine, but it's counterintuitive. Writing the level when the saves _change_ is much more intuitive.

**Comment by Forelius** [comment]
One addition I have in mind is to provide a different character sheet that uses the same data, but has a more customizable layout. This might not be a v1 thing.
