### ISSUE TITLE
Feature Request: Re-Roll Initiative Each Roll

### ISSUE THREAD

**Issue by sirkerry** [Forelius/fantastic-depths#6]
Would it be possible to have a Configure Settings or Combat Tracker Setting to have the CT automatically re-roll initiative at the end of each combat round?

**Comment by Forelius** [comment]
Added to the backlog. Thanks

**Comment by Forelius** [comment]
I added an option, default to true, that resets the initiative on the next round. No automatic reroll option yet, but one step closer to that.

**Comment by Forelius** [comment]
This was implemented, committed to the repo and will be available in the next release.

**Comment by Forelius** [comment]
Released in v0.4.1.
