### ISSUE TITLE
Suggestion: add a "to-hit" modifier to weapons

### ISSUE THREAD

**Issue by JordanRR** [Forelius/fantastic-depths#60]
This way, magic weapons would be much easier to create and implement. (Unless there is already a way that I ignore.)

**Comment by Forelius** [comment]
To-hit and damage modifiers are done with effects. See the FADE Compendium magic weapons for an example. There are separate modifiers for melee and missile attack rolls and damage rolls.

**Comment by Forelius** [comment]
By the way, I originally implemented it as four different fields, but then there were other things I needed it to do and effects ended up being the most flexible way.

**Comment by JordanRR** [comment]
Hum, weird. That how I tried to implement it before I wrote the issue, and the bonus was affecting all rolls, not just the ones using the item. I must have used a wrong name in the field. 

Anyway, thank you very much!

**Comment by Forelius** [comment]
On the effect's details tab, make sure that "Apply Effect to Actor" is unchecked. You want the effect applied to the item itself.
